
#define GUI_CFG_USE_ID 1
#define GUI_CFG_DISPLAY_W   128
#define GUI_CFG_DISPLAY_H   64

#define GUI_CFG_TICK_MAX        0xFFFFFFFF /* 32-bit CPU */

#define GUI_CFG_USE_LOG   0

#define GUI_CFG_USE_PAGE_MANAGER 1

#define GUI_CFG_USE_ANIM   1
#define GUI_CFG_USE_SW   1
#define GUI_CFG_USE_CHECK_BOX 1
#define GUI_CFG_USE_BITMAP 1
#define GUI_CFG_USE_FREE_STYLE 1
#define GUI_CFG_USE_LABEL 1
#define GUI_CFG_USE_SLIDER 1
#define GUI_CFG_USE_IDCTOR 1
#define GUI_CFG_USE_POPUP 1
#define GUI_CFG_USE_GROUP 1